### ISSUE TITLE
BEGIN TRANSACTION; neaiškumai...

### ISSUE THREAD

**Issue by dz0** [donatasbartkus/ktu-prisijungimo-forma#5]
Bandant ją naudoti su PHPMyAdmin: SQL vykdymas neveikia.., o be jos (ir COMMIT) - veikia
pvz:
https://github.com/donatasbartkus/ktu-prisijungimo-forma/blob/JM/db/db%20sql.sql

**Comment by donatasbartkus** [comment]
o kam jus naudojate tranzakcijas?

Su pagarba,
Donatas Bartkus

**Comment by dz0** [comment]
atrodo, jei DB struktūrą iš http://sqlitebrowser.org/ eksportuoji, prideda...

pas kelis tas pats buvo, tai galvojau, gal tu pridėjai kaip kokį "good practice" :)

**Comment by donatasbartkus** [comment]
Siuo atveju tranzakcijos visiskai nereikalingos :)
